insert into USER_ROLE values(1,'Organizer');
insert into USER_ROLE values(2,'Coach');
insert into USER_ROLE values(3,'Guest');

insert into USER_ACCOUNT values(1,'Gianna Daskalaki','Athens',1,to_date('29-AUG-04','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(2,'Hu Jintao','Beijing',1,to_date('24-AUG-08','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(3,'Sebastian Coe','London',1,to_date('12-AUG-12','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(4,'Carlos Nuzman','Rio',1,to_date('21-AUG-16','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(5,'Peng Bo','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(6,'Alexandre Despatie','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(7,'Dmitri Sautin','GUEST',3,to_date('30-MAR-2020','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(8,'Hu Jia','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(9,'Mathew Helm','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(10,'Tian Liang','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(11,'Thomas Bimis','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(12,'Nikolaos Siranidis','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(13,'Tobias Schellenberg','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(14,'Andreas Wels','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(15,'Steven Barnett','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(16,'Robert Newbery','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(17,'Yang Jinghui','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(18,'Peter Waterfield','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(19,'Leon Taylor','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(20,'Chantelle Michell','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(21,'Lao Lishi','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(22,'Loudy Tourky','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(23,'Li Ting','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(24,'Natalia Goncharova','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(25,'Yulia Koltunova','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(26,'Blythe Hartley','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(27,'Emilie Heymans','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(28,'He Chong','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(29,'Qin Kai','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(30,'Matthew Mitcham','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(31,'Zhou Lvxin','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(32,'Gleb Galperin','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(33,'Wang Feng','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into user_account values(34,'Yuriy Kunakov','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(35,'Lin Yue','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(36,'Huo Liang','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(37,'Patrick Hausding','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(38,'Sascha Klein','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(39,'Dmitriy Dobroskok','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(40,'Chen Ruolin','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(41,'Wang Xin','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(42,'Briony Cole','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(43,'Melissa Wu','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(44,'Paola Espinosa','GUEST',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(45,'Tatiana Ortiz','guest',3,to_date('30-MAR-20','dd-mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(46,'Ilya Zakharov','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(47,'David Boudia','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(48,'Qiu Bo','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(49,'Tom Daley','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(50,'Luo Yutong','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(51,'Evgeny Kuznetsov','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(52,'Troy Dumais','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(53,'Kristian Ipsen','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(54,'Cao Yuan','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(55,'Zhang Yanquan','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(56,'Iván García','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(57,'Germán Sánchez','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(58,'Nick McCrory','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(59,'Brittany Broben','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(60,'Pandelela Rinong','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(61,'Wang Hao','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(62,'du Espinosa','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(63,'Alejandra Orozco','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(64,'Meaghan Benfeito','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(65,'Roseline Filion','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(66,'Jack Laugher','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(67,'Chen Aisen','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(68,'Sam Dorman','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(69,'Michael Hixon','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(70,'Steele Johnson','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(71,'Daniel Goodfellow','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(72,'Ren Qian','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(73,'Si Yajie','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(74,'Liu Huixia','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(75,'Cheong JunHoong','GUEST',3,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(76,'coach 1','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(77,'coach 2','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(78,'coach 3','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(79,'coach 4','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(80,'coach 5','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(81,'coach 6','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(82,'coach 7','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(83,'coach 8','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(84,'coach 9','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(85,'coach 10','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(86,'coach 11','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into USER_ACCOUNT values(87,'coach 12','COACH',2,to_date('30-MAR-20','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));

insert into OLYMPICS values(1,'I','Athens',to_date('13-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),to_date('29-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),'https://www.olympic.org/beijing-2008');
insert into OLYMPICS values(2,'II','Beijing',to_date('08-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),to_date('24-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),'https://www.olympic.org/london-2012');
insert into OLYMPICS values(3,'III','London',to_date('27-JUL-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),to_date('12-AUG-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),'https://www.olympic.org/rio-2016');
insert into OLYMPICS values(4,'IV','Rio',to_date('05-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),to_date('21-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'),'https://www.olympic.org/paris-2022');

insert into SPORT values(1,'3m men diving','3m men diving',to_date('01-JAN-1926','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),1);
insert into SPORT values(2,'10m women diving','10m women diving',to_date('01-JAN-1896','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),1);
insert into SPORT values(3,'10m men diving','10m men diving',to_date('01-JAN-1877','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),1);
insert into SPORT values(4,'3m doubles men diving','3m doubles men diving',to_date('01-JAN-1926','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),2);
insert into SPORT values(5,'10m doubles women diving','10m doubles women diving',to_date('01-JAN-1992','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),2);
insert into SPORT values(6,'10m doubles men diving','10m doubles men diving',to_date('01-JAN-1877','dd-Mon-yyyy','NLS_DATE_LANGUAGE=AMERICAN'),2);

insert into PARTICIPANT values(5,'Peng','Bo','China','Nanchang',to_date('18-FEB-1981','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(6,'Alexandre','Despatie','Canada','Laval',to_date('08-JUN-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(7,'Dmitri','Sautin','Russia','Voronezh',to_date('15-MAR-1974','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(8,'Hu','Jia','China','Wuhan',to_date('10-JAN-1983','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(9,'Mathew','Helm','Australia','Bourke',to_date('09-DEC-1980','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(10,'Tian','Liang','China','Chongqing',to_date('27-AUG-1979','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(11,'Thomas','Bimis','Greece','Athens',to_date('11-JUN-1975','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(12,'Nikolaos','Siranidis','Greece','Athens',to_date('26-FEB-1976','dd-mon-yyyy','nls_date_language=american'));;
insert into PARTICIPANT values(13,'Tobias','Schellenberg','Germany','Leipzig',to_date('17-NOV-1978','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(14,'Andreas','Wels','Germany','Schonebeck',to_date('01-JAN-1975','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(15,'Steven','Barnett','Australia','Croydon Park',to_date('15-JUN-1979','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(16,'Robert','Newbery','Australia','Adelaide',to_date('02-JAN-1979','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(17,'Yang','Jinghui','China','Guangzhou',to_date('15-MAR-1983','dd-mon-yy','nls_date_language=american'));
insert into PARTICIPANT values(18,'Peter','Waterfield','United Kindom','Waltham Forest',to_date('12-MAR-1981','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(19,'Leon','Taylor','United Kindom','Cheltenhan',to_date('02-NOV-1977','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(20,'Chantelle','Michell','Australia','Melbourne',to_date('06-MAY-1977','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(21,'Lao','Lishi','China','Zhanjiang',to_date('12-DEC-1987','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(22,'Loudy','Tourky','Australia','Melbourne',to_date('07-JUL-1979','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(23,'Li','Ting','China','Guilin',to_date('01-APR-1987','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(24,'Natalia','Goncharova','Russia','Voronezh',to_date('29-JAN-1988','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(25,'Yulia','Nikolayevna','Russia','Volgograd',to_date('04-MAY-1989','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(26,'Blythe','Hartley','Canada','Alberta',to_date('02-MAY-1982','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(27,'Emilie','Heymans','Canada','Brussels',to_date('14-DEC-1981','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(28,'He','Chong','China','Zhanjiang',to_date('10-JUN-1987','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(29,'Qin','Kai','China','Xian',to_date('31-JAN-1986','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(30,'Matthew','Mitcham','Australia','Brisbane',to_date('02-MAR-1988','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(31,'Zhou','Lvxin','China','Wuhu',to_date('31-JUL-1988','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(32,'Gleb','Galperin','Russia','Moscow',to_date('25-MAY-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(33,'Wang','Feng','China','Taian',to_date('17-APR-1979','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(34,'Yuriy','Kunakov','Russia','Russia',to_date('19-FEB-1990','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(35,'Lin','Yue','China','Chaozhou',to_date('24-JUL-1991','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(36,'Huo','Liang','China','Shanghai',to_date('29-SEP-1989','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(37,'Patrick','Hausding','Germany','Berlin',to_date('09-MAR-1989','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(38,'Sascha','Klein','Germany','Eschweiler',to_date('12-SEP-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(39,'Dmitriy','Dobroskok','Russia','Buzuluk',to_date('01-MAR-1984','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(40,'Chen','Ruolin','China','Nantong',to_date('12-DEC-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(41,'Wang','Xin','China','Wuhan',to_date('11-AUG-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(42,'Briony','Cole','Australia','Melbourne',to_date('28-FEB-1983','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(43,'Melissa','Wu','Australia','Sydney',to_date('03-MAY-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(44,'Paola','Espinosa','Mexico','La Paz',to_date('31-JUL-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(45,'Tatiana','Ortiz','Mexico','Mexico City',to_date('12-JAN-1984','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(46,'Ilya ','Zakharov','Russia','Xian',to_date('02-MAY-1991','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(47,'David ','Boudia','United States','Noblesville',to_date('24-APR-1989','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(48,'Qiu',' Bo','China','Neijiang',to_date('31-JAn-1993','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(49,'Tom',' Daley','United Kingdom','Zhanjiang',to_date('21-MAY-1994','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(50,'Luo',' Yutong','China','Huizhou',to_date('06-OCT-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(51,'Evgeny ','Kuznetsov','Russia','Stavropol',to_date('12-APR-1990','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(52,'Troy ','Dumais','United States','Ventura',to_date('21-JAN-1980','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(53,'Kristian',' Ipsen','United States','Clayton',to_date('20-OCT-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(54,'Cao',' Yuan','China','Changsha',to_date('07-FEB-1985','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(55,'Zhang ','Yanquan','China','Chaozhou',to_date('13-JUN-1994','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(56,'Iván',' García','Mexico','Guadalajara',to_date('25-OCT-1993','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(57,'Germán ','Sánchez','Mexico','Guadalajara',to_date('24-JUN-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(58,'Nick',' McCrory','United States','Chapel Hill',to_date('09-AUG-1991','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(59,'Brittany',' Broben','	Australia','Gold Coast',to_date('23-NOV-1995','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(60,'Pandelela',' Rinong','Malaysian','Bau',to_date('02-MAR-1993','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(61,'Wang',' Hao','China','Tianjin',to_date('26-DEC-1992','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(62,'du','Espinosa','Mexico','Guadalajara',to_date('30-MAR-1993','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(63,'Alejandra',' Orozco','Mexico','Guadalajara',to_date('19-APR-1997','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(64,'Meaghan',' Benfeito','Canada','Montreal',to_date('02-MAR-1989','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(65,'Roseline',' Filion','Canada','Laval',to_date('03-JUL-1987','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(66,'Jack',' Laugher','United Kingdom','Harrogate',to_date('30-JAN-1995','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(67,'Chen',' Aisen','China','Guangzhou',to_date('22-OCT-1995','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(68,'Sam',' Dorman','United States','Marla',to_date('30-AUG-1991','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(69,'Michael',' Hixon','United States','Amherst',to_date('16-JUL-1994','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(70,'Steele',' Johnson','United States','Indianapolis',to_date('16-JUN-1996','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(71,'Daniel',' Goodfellow','United Kingdom','Cambridge',to_date('19-OCT-1996','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(72,'Ren',' Qian','China',' Chengdu',to_date('20-FEB-2001','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(73,'Si',' Yajie','China','Xian',to_date('04-DEC-1998','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(74,'Liu',' Huixia','China','Beijing',to_date('30-NOV-1997','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(75,'Cheong',' JunHoong','Malaysia','Ipoh',to_date('16-APR-1990','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(76,'coach 1','1','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(77,'coach 2','2','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(78,'coach 3','3','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(79,'coach 4','4','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(80,'coach 5','5','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(81,'coach 6','6','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(82,'coach 7','7','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(83,'coach 8','8','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(84,'coach 9','9','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(85,'coach 10','10','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(86,'coach 11','11','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));
insert into PARTICIPANT values(87,'coach 12','12','China','Beijing',to_date('30-MAR-1969','dd-mon-yyyy','nls_date_language=american'));


insert into COUNTRY values(1,'China','CHN');
insert into COUNTRY values(2,'Australia','AUS');
insert into COUNTRY values(3,'Russia','RUS');
insert into COUNTRY values(4,'Canada','CAN');
insert into COUNTRY values(5,'Germany','GER');
insert into COUNTRY values(6,'Mexico','MEX');

insert into TEAM values(1,1,'A1',1,1,76);
insert into TEAM values(2,1,'A2',1,2,76);
insert into TEAM values(3,1,'A3',1,3,76);
insert into TEAM values(4,1,'A4',1,4,76);
insert into TEAM values(5,1,'A5',1,5,76);
insert into TEAM values(6,1,'A6',1,6,76);
insert into TEAM values(7,1,'A1',2,1,76);
insert into TEAM values(8,1,'A2',2,2,76);
insert into TEAM values(9,1,'A9',2,3,76);
insert into TEAM values(10,1,'A10',2,4,76);
insert into TEAM values(11,1,'A11',2,5,76);
insert into TEAM values(12,1,'A12',2,6,76);
insert into TEAM values(13,1,'A13',3,1,76);
insert into TEAM values(14,1,'A14',3,2,76);
insert into TEAM values(15,1,'A15',3,3,77);
insert into TEAM values(16,1,'A16',3,4,77);
insert into TEAM values(17,1,'A17',3,5,77);
insert into TEAM values(18,1,'A18',3,6,77);
insert into TEAM values(19,1,'A19',4,1,77);
insert into TEAM values(20,1,'A20',4,2,77);
insert into TEAM values(21,1,'A21',4,3,77);
insert into TEAM values(22,1,'A22',4,4,77);
insert into TEAM values(23,1,'A23',4,5,77);
insert into TEAM values(24,1,'A24',4,6,77);
insert into TEAM values(25,1,'A25',5,1,77);
insert into TEAM values(26,1,'A26',5,2,77);
insert into TEAM values(27,1,'A27',5,3,77);
insert into TEAM values(28,1,'A28',5,4,77);
insert into TEAM values(29,1,'A29',5,5,78);
insert into TEAM values(30,1,'A30',5,6,78);
insert into TEAM values(31,1,'A31',6,1,78);
insert into TEAM values(32,1,'A32',6,2,78);
insert into TEAM values(33,1,'A33',6,3,78);
insert into TEAM values(34,1,'A34',6,4,78);
insert into TEAM values(35,1,'A35',6,5,78);
insert into TEAM values(36,1,'A36',6,6,78);
insert into TEAM values(37,2,'B1',1,1,78);
insert into TEAM values(38,2,'B2',1,2,78);
insert into TEAM values(39,2,'B3',1,3,78);
insert into TEAM values(40,2,'B4',1,4,78);
insert into TEAM values(41,2,'B5',1,5,78);
insert into TEAM values(42,2,'B6',1,6,78);
insert into TEAM values(43,2,'B7',2,1,79);
insert into TEAM values(44,2,'B8',2,2,79);
insert into TEAM values(45,2,'B9',2,3,79);
insert into TEAM values(46,2,'B10',2,4,79);
insert into TEAM values(47,2,'B11',2,5,79);
insert into TEAM values(48,2,'B12',2,6,79);
insert into TEAM values(49,2,'B13',3,1,79);
insert into TEAM values(50,2,'B14',3,2,79);
insert into TEAM values(51,2,'B15',3,3,79);
insert into TEAM values(52,2,'B16',3,4,79);
insert into TEAM values(53,2,'B17',3,5,79);
insert into TEAM values(54,2,'B18',3,6,79);
insert into TEAM values(55,2,'A19',4,1,79);
insert into TEAM values(56,2,'B20',4,2,79);
insert into TEAM values(57,2,'B21',4,3,80);
insert into TEAM values(58,2,'B22',4,4,80);
insert into TEAM values(59,2,'B23',4,5,80);
insert into TEAM values(60,2,'B24',4,6,80);
insert into TEAM values(61,2,'B25',5,1,80);
insert into TEAM values(62,2,'B26',5,2,80);
insert into TEAM values(63,2,'B27',5,3,80);
insert into TEAM values(64,2,'B28',5,4,80);
insert into TEAM values(65,2,'B29',5,5,80);
insert into TEAM values(66,2,'B30',5,6,80);
insert into TEAM values(67,2,'B31',6,1,80);
insert into TEAM values(68,2,'B32',6,2,80);
insert into TEAM values(69,2,'B33',6,3,80);
insert into TEAM values(70,2,'B34',6,4,80);
insert into TEAM values(71,2,'B35',6,5,81);
insert into TEAM values(72,2,'B36',6,6,81);
insert into TEAM values(73,3,'C1',1,1,81);
insert into TEAM values(74,3,'C2',1,2,81);
insert into TEAM values(75,3,'C3',1,3,81);
insert into TEAM values(76,3,'C4',1,4,81);
insert into TEAM values(77,3,'C5',1,5,81);
insert into TEAM values(78,3,'C6',1,6,81);
insert into TEAM values(79,3,'C7',2,1,81);
insert into TEAM values(80,3,'C8',2,2,81);
insert into TEAM values(81,3,'C9',2,3,81);
insert into TEAM values(82,3,'C10',2,4,81);
insert into TEAM values(83,3,'C11',2,5,81);
insert into TEAM values(84,3,'C12',2,6,81);
insert into TEAM values(85,3,'C13',3,1,81);
insert into TEAM values(86,3,'C14',3,2,82);
insert into TEAM values(87,3,'C15',3,3,82);
insert into TEAM values(88,3,'C16',3,4,82);
insert into TEAM values(89,3,'C17',3,5,82);
insert into TEAM values(90,3,'C18',3,6,82);
insert into TEAM values(91,3,'C19',4,1,82);
insert into TEAM values(92,3,'C20',4,2,82);
insert into TEAM values(93,3,'C21',4,3,82);
insert into TEAM values(94,3,'C22',4,4,82);
insert into TEAM values(95,3,'C23',4,5,82);
insert into TEAM values(96,3,'C24',4,6,82);
insert into TEAM values(97,3,'C25',5,1,82);
insert into TEAM values(98,3,'C26',5,2,82);
insert into TEAM values(99,3,'C27',5,3,82);
insert into TEAM values(100,3,'C28',5,4,83);
insert into TEAM values(101,3,'C29',5,5,83);
insert into TEAM values(102,3,'C30',5,6,83);
insert into TEAM values(103,3,'C31',6,1,83);
insert into TEAM values(104,3,'C32',6,2,83);
insert into TEAM values(105,3,'C33',6,3,83);
insert into TEAM values(106,3,'C34',6,4,83);
insert into TEAM values(107,3,'C35',6,5,83);
insert into TEAM values(108,3,'C36',6,6,83);
insert into TEAM values(109,4,'D1',1,1,83);
insert into TEAM values(110,4,'D2',1,2,83);
insert into TEAM values(111,4,'D3',1,3,83);
insert into TEAM values(112,4,'D4',1,4,83);
insert into TEAM values(113,4,'D5',1,5,83);
insert into TEAM values(114,4,'D6',1,6,83);
insert into TEAM values(115,4,'D7',2,1,84);
insert into TEAM values(116,4,'D8',2,2,84);
insert into TEAM values(117,4,'D9',2,3,84);
insert into TEAM values(118,4,'D10',2,4,84);
insert into TEAM values(119,4,'D11',2,5,84);
insert into TEAM values(120,4,'D12',2,6,84);
insert into TEAM values(121,4,'D13',3,1,84);
insert into TEAM values(122,4,'D14',3,2,84);
insert into TEAM values(123,4,'D15',3,3,84);
insert into TEAM values(124,4,'D16',3,4,84);
insert into TEAM values(125,4,'D17',3,5,84);
insert into TEAM values(126,4,'D18',3,6,84);
insert into TEAM values(127,4,'D19',4,1,84);
insert into TEAM values(128,4,'D20',4,2,84);
insert into TEAM values(129,4,'D21',4,3,85);
insert into TEAM values(130,4,'D22',4,4,85);
insert into TEAM values(131,4,'D23',4,5,85);
insert into TEAM values(132,4,'D24',4,6,85);
insert into TEAM values(133,4,'D25',5,1,85);
insert into TEAM values(134,4,'D26',5,2,85);
insert into TEAM values(135,4,'D27',5,3,85);
insert into TEAM values(136,4,'D28',5,4,85);
insert into TEAM values(137,4,'D29',5,5,85);
insert into TEAM values(138,4,'D30',5,6,85);
insert into TEAM values(139,4,'D31',6,1,85);
insert into TEAM values(140,4,'D32',6,2,86);
insert into TEAM values(141,4,'D33',6,3,86);
insert into TEAM values(142,4,'D34',6,4,86);
insert into TEAM values(143,4,'D35',6,5,86);
insert into TEAM values(144,4,'D36',6,6,86);


insert into TEAM_MEMBER values(1,5);
insert into TEAM_MEMBER values(2,24);
insert into TEAM_MEMBER values(3,11);
insert into TEAM_MEMBER values(3,13);
insert into TEAM_MEMBER values(5,24);
insert into TEAM_MEMBER values(5,26);
insert into TEAM_MEMBER values(6,13);
insert into TEAM_MEMBER values(6,20);
insert into TEAM_MEMBER values(8,23);
insert into TEAM_MEMBER values(8,25);
insert into TEAM_MEMBER values(9,12);
insert into TEAM_MEMBER values(10,18);
insert into TEAM_MEMBER values(10,19);
insert into TEAM_MEMBER values(12,12);
insert into TEAM_MEMBER values(12,19);
insert into TEAM_MEMBER values(13,7);
insert into TEAM_MEMBER values(17,27);
insert into TEAM_MEMBER values(17,28);
insert into TEAM_MEMBER values(19,6);
insert into TEAM_MEMBER values(23,29);
insert into TEAM_MEMBER values(23,30);
insert into TEAM_MEMBER values(28,16);
insert into TEAM_MEMBER values(28,17);
insert into TEAM_MEMBER values(37,31);
insert into TEAM_MEMBER values(37,32);
insert into TEAM_MEMBER values(38,43);
insert into TEAM_MEMBER values(38,44);
insert into TEAM_MEMBER values(39,34);
insert into TEAM_MEMBER values(40,36);
insert into TEAM_MEMBER values(40,32);
insert into TEAM_MEMBER values(41,44);
insert into TEAM_MEMBER values(41,43);
insert into TEAM_MEMBER values(42,38);
insert into TEAM_MEMBER values(42,39);
insert into TEAM_MEMBER values(45,33);
insert into TEAM_MEMBER values(47,45);
insert into TEAM_MEMBER values(47,46);
insert into TEAM_MEMBER values(51,35);
insert into TEAM_MEMBER values(52,42);
insert into TEAM_MEMBER values(52,37);
insert into TEAM_MEMBER values(54,35);
insert into TEAM_MEMBER values(54,42);
insert into TEAM_MEMBER values(55,6);
insert into TEAM_MEMBER values(56,30);
insert into TEAM_MEMBER values(66,40);
insert into TEAM_MEMBER values(66,41);
insert into TEAM_MEMBER values(71,47);
insert into TEAM_MEMBER values(71,48);
insert into TEAM_MEMBER values(73,32);
insert into TEAM_MEMBER values(73,31);
insert into TEAM_MEMBER values(74,43);
insert into TEAM_MEMBER values(75,52);
insert into TEAM_MEMBER values(76,54);
insert into TEAM_MEMBER values(76,32);
insert into TEAM_MEMBER values(77,43);
insert into TEAM_MEMBER values(77,66);
insert into TEAM_MEMBER values(78,58);
insert into TEAM_MEMBER values(78,59);
insert into TEAM_MEMBER values(80,64);
insert into TEAM_MEMBER values(85,49);
insert into TEAM_MEMBER values(88,49);
insert into TEAM_MEMBER values(88,55);
insert into TEAM_MEMBER values(95,69);
insert into TEAM_MEMBER values(95,70);
insert into TEAM_MEMBER values(107,47);
insert into TEAM_MEMBER values(107,68);
insert into TEAM_MEMBER values(108,60);
insert into TEAM_MEMBER values(108,61);
insert into TEAM_MEMBER values(109,58);
insert into TEAM_MEMBER values(110,79);
insert into TEAM_MEMBER values(110,80);
insert into TEAM_MEMBER values(111,73);
insert into TEAM_MEMBER values(112,58);
insert into TEAM_MEMBER values(112,32);
insert into TEAM_MEMBER values(113,43);
insert into TEAM_MEMBER values(113,81);
insert into TEAM_MEMBER values(114,73);
insert into TEAM_MEMBER values(114,38);
insert into TEAM_MEMBER values(128,69);
insert into TEAM_MEMBER values(131,69);
insert into TEAM_MEMBER values(131,70);
insert into TEAM_MEMBER values(133,40);
insert into TEAM_MEMBER values(141,61);


insert into MEDAL values (1,'Gold',3);
insert into MEDAL values (2,'Silver',2);
insert into MEDAL values (3,'Bronze',1);

insert into VENUE values(1,1,'Greek national ',3);
insert into VENUE values(2,2,'Beijing national',4);
insert into VENUE values(3,3,'London national',4);
insert into VENUE values(4,4,'Rio national',3);


insert into EVENT values(1,1,1,1,to_date('24-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(2,2,1,1,to_date('28-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(3,3,1,1,to_date('22-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(4,4,1,1,to_date('16-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(5,5,1,1,to_date('14-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(6,6,1,1,to_date('16-AUG-04','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(7,1,2,1,to_date('19-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(8,2,2,1,to_date('23-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(9,3,2,2,to_date('21-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(10,4,2,1,to_date('13-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(11,5,2,1,to_date('11-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(12,6,2,2,to_date('12-AUG-08','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(13,1,3,1,to_date('07-AUG-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(14,2,3,1,to_date('11-AUG-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(15,3,3,1,to_date('09-AUG-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(16,4,3,1,to_date('01-AUG-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(17,5,3,1,to_date('30-JUL-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(18,6,3,1,to_date('31-JUL-12','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(19,1,4,1,to_date('16-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(20,2,4,1,to_date('20-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(21,3,4,2,to_date('18-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(22,4,4,1,to_date('10-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(23,5,4,1,to_date('08-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));
insert into EVENT values(24,6,4,2,to_date('08-AUG-16','dd-Mon-yy','NLS_DATE_LANGUAGE=AMERICAN'));

insert into EVENT_PARTICIPATION values(1,1,'e');
insert into EVENT_PARTICIPATION values(1,2,'e');
insert into EVENT_PARTICIPATION values(1,3,'e');
insert into EVENT_PARTICIPATION values(1,4,'e');
insert into EVENT_PARTICIPATION values(1,5,'e');
insert into EVENT_PARTICIPATION values(1,6,'e');
insert into EVENT_PARTICIPATION values(2,7,'e');
insert into EVENT_PARTICIPATION values(2,8,'e');
insert into EVENT_PARTICIPATION values(2,9,'e');
insert into EVENT_PARTICIPATION values(2,10,'e');
insert into EVENT_PARTICIPATION values(2,11,'e');
insert into EVENT_PARTICIPATION values(2,12,'e');
insert into EVENT_PARTICIPATION values(3,13,'e');
insert into EVENT_PARTICIPATION values(3,14,'e');
insert into EVENT_PARTICIPATION values(3,15,'e');
insert into EVENT_PARTICIPATION values(3,16,'e');
insert into EVENT_PARTICIPATION values(3,17,'e');
insert into EVENT_PARTICIPATION values(3,18,'e');
insert into EVENT_PARTICIPATION values(4,19,'e');
insert into EVENT_PARTICIPATION values(4,20,'e');
insert into EVENT_PARTICIPATION values(4,21,'e');
insert into EVENT_PARTICIPATION values(4,22,'e');
insert into EVENT_PARTICIPATION values(4,23,'e');
insert into EVENT_PARTICIPATION values(4,24,'e');
insert into EVENT_PARTICIPATION values(5,25,'e');
insert into EVENT_PARTICIPATION values(5,26,'e');
insert into EVENT_PARTICIPATION values(5,27,'e');
insert into EVENT_PARTICIPATION values(5,28,'e');
insert into EVENT_PARTICIPATION values(5,29,'e');
insert into EVENT_PARTICIPATION values(5,30,'e');
insert into EVENT_PARTICIPATION values(6,31,'e');
insert into EVENT_PARTICIPATION values(6,32,'e');
insert into EVENT_PARTICIPATION values(6,33,'e');
insert into EVENT_PARTICIPATION values(6,34,'e');
insert into EVENT_PARTICIPATION values(6,35,'n');
insert into EVENT_PARTICIPATION values(6,36,'n');
insert into EVENT_PARTICIPATION values(7,37,'e');
insert into EVENT_PARTICIPATION values(7,38,'e');
insert into EVENT_PARTICIPATION values(7,39,'e');
insert into EVENT_PARTICIPATION values(7,40,'e');
insert into EVENT_PARTICIPATION values(7,41,'e');
insert into EVENT_PARTICIPATION values(7,42,'e');
insert into EVENT_PARTICIPATION values(8,43,'e');
insert into EVENT_PARTICIPATION values(8,44,'e');
insert into EVENT_PARTICIPATION values(8,45,'e');
insert into EVENT_PARTICIPATION values(8,46,'e');
insert into EVENT_PARTICIPATION values(8,47,'e');
insert into EVENT_PARTICIPATION values(8,48,'e');
insert into EVENT_PARTICIPATION values(9,49,'e');
insert into EVENT_PARTICIPATION values(9,50,'e');
insert into EVENT_PARTICIPATION values(9,51,'e');
insert into EVENT_PARTICIPATION values(9,52,'e');
insert into EVENT_PARTICIPATION values(9,53,'e');
insert into EVENT_PARTICIPATION values(9,54,'e');
insert into EVENT_PARTICIPATION values(10,55,'e');
insert into EVENT_PARTICIPATION values(10,56,'e');
insert into EVENT_PARTICIPATION values(10,57,'e');
insert into EVENT_PARTICIPATION values(10,58,'e');
insert into EVENT_PARTICIPATION values(10,59,'e');
insert into EVENT_PARTICIPATION values(10,60,'n');
insert into EVENT_PARTICIPATION values(11,61,'e');
insert into EVENT_PARTICIPATION values(11,62,'e');
insert into EVENT_PARTICIPATION values(11,63,'n');
insert into EVENT_PARTICIPATION values(11,64,'e');
insert into EVENT_PARTICIPATION values(11,65,'e');
insert into EVENT_PARTICIPATION values(11,66,'e');
insert into EVENT_PARTICIPATION values(12,67,'e');
insert into EVENT_PARTICIPATION values(12,68,'e');
insert into EVENT_PARTICIPATION values(12,69,'e');
insert into EVENT_PARTICIPATION values(12,70,'n');
insert into EVENT_PARTICIPATION values(12,71,'e');
insert into EVENT_PARTICIPATION values(12,72,'n');
insert into EVENT_PARTICIPATION values(13,73,'e');
insert into EVENT_PARTICIPATION values(13,74,'e');
insert into EVENT_PARTICIPATION values(13,75,'e');
insert into EVENT_PARTICIPATION values(13,76,'e');
insert into EVENT_PARTICIPATION values(13,77,'e');
insert into EVENT_PARTICIPATION values(13,78,'e');
insert into EVENT_PARTICIPATION values(14,79,'e');
insert into EVENT_PARTICIPATION values(14,80,'e');
insert into EVENT_PARTICIPATION values(14,81,'e');
insert into EVENT_PARTICIPATION values(14,82,'e');
insert into EVENT_PARTICIPATION values(14,83,'e');
insert into EVENT_PARTICIPATION values(14,84,'e');
insert into EVENT_PARTICIPATION values(15,85,'e');
insert into EVENT_PARTICIPATION values(15,86,'e');
insert into EVENT_PARTICIPATION values(15,87,'e');
insert into EVENT_PARTICIPATION values(15,88,'e');
insert into EVENT_PARTICIPATION values(15,89,'e');
insert into EVENT_PARTICIPATION values(15,90,'e');
insert into EVENT_PARTICIPATION values(16,91,'e');
insert into EVENT_PARTICIPATION values(16,92,'n');
insert into EVENT_PARTICIPATION values(16,93,'e');
insert into EVENT_PARTICIPATION values(16,94,'e');
insert into EVENT_PARTICIPATION values(16,95,'n');
insert into EVENT_PARTICIPATION values(16,96,'e');
insert into EVENT_PARTICIPATION values(17,97,'e');
insert into EVENT_PARTICIPATION values(17,98,'e');
insert into EVENT_PARTICIPATION values(17,99,'n');
insert into EVENT_PARTICIPATION values(17,100,'e');
insert into EVENT_PARTICIPATION values(17,101,'e');
insert into EVENT_PARTICIPATION values(17,102,'e');
insert into EVENT_PARTICIPATION values(18,103,'e');
insert into EVENT_PARTICIPATION values(18,104,'n');
insert into EVENT_PARTICIPATION values(18,105,'e');
insert into EVENT_PARTICIPATION values(18,106,'n');
insert into EVENT_PARTICIPATION values(18,107,'e');
insert into EVENT_PARTICIPATION values(18,108,'e');
insert into EVENT_PARTICIPATION values(19,109,'e');
insert into EVENT_PARTICIPATION values(19,110,'e');
insert into EVENT_PARTICIPATION values(19,111,'e');
insert into EVENT_PARTICIPATION values(19,112,'e');
insert into EVENT_PARTICIPATION values(19,113,'e');
insert into EVENT_PARTICIPATION values(19,114,'e');
insert into EVENT_PARTICIPATION values(20,115,'e');
insert into EVENT_PARTICIPATION values(20,116,'e');
insert into EVENT_PARTICIPATION values(20,117,'e');
insert into EVENT_PARTICIPATION values(20,118,'e');
insert into EVENT_PARTICIPATION values(20,119,'e');
insert into EVENT_PARTICIPATION values(20,120,'e');
insert into EVENT_PARTICIPATION values(21,121,'e');
insert into EVENT_PARTICIPATION values(21,122,'e');
insert into EVENT_PARTICIPATION values(21,123,'e');
insert into EVENT_PARTICIPATION values(21,124,'e');
insert into EVENT_PARTICIPATION values(21,125,'e');
insert into EVENT_PARTICIPATION values(21,126,'e');
insert into EVENT_PARTICIPATION values(22,127,'e');
insert into EVENT_PARTICIPATION values(22,128,'n');
insert into EVENT_PARTICIPATION values(22,129,'e');
insert into EVENT_PARTICIPATION values(22,130,'n');
insert into EVENT_PARTICIPATION values(22,131,'e');
insert into EVENT_PARTICIPATION values(22,132,'e');
insert into EVENT_PARTICIPATION values(23,133,'e');
insert into EVENT_PARTICIPATION values(23,134,'n');
insert into EVENT_PARTICIPATION values(23,135,'n');
insert into EVENT_PARTICIPATION values(23,136,'e');
insert into EVENT_PARTICIPATION values(23,137,'n');
insert into EVENT_PARTICIPATION values(23,138,'e');
insert into EVENT_PARTICIPATION values(24,139,'e');
insert into EVENT_PARTICIPATION values(24,140,'n');
insert into EVENT_PARTICIPATION values(24,141,'e');
insert into EVENT_PARTICIPATION values(24,142,'n');
insert into EVENT_PARTICIPATION values(24,143,'e');
insert into EVENT_PARTICIPATION values(24,144,'e');

insert into scoreboard values(1,1,1,5,1,1);
insert into scoreboard values(1,1,19,6,2,2);
insert into scoreboard values(1,1,13,7,3,3);
insert into scoreboard values(1,2,8,23,1,1);
insert into scoreboard values(1,2,2,24,2,2);
insert into scoreboard values(1,2,8,25,3,3);
insert into scoreboard values(1,3,3,11,1,1);
insert into scoreboard values(1,3,9,12,2,2);
insert into scoreboard values(1,3,3,13,3,3);
insert into scoreboard values(1,4,28,16,2,2);
insert into scoreboard values(1,4,28,17,2,2);
insert into scoreboard values(1,4,10,18,3,3);
insert into scoreboard values(1,4,10,19,3,3);
insert into scoreboard values(1,5,5,24,1,1);
insert into scoreboard values(1,5,5,26,1,1);
insert into scoreboard values(1,5,17,27,2,2);
insert into scoreboard values(1,5,17,28,2,2);
insert into scoreboard values(1,5,23,29,3,3);
insert into scoreboard values(1,5,23,30,3,3);
insert into scoreboard values(1,6,6,13,1,1);
insert into scoreboard values(1,6,6,20,1,1);
insert into scoreboard values(1,6,12,12,3,3);
insert into scoreboard values(1,6,12,19,3,3);
insert into scoreboard values(2,7,37,31,1,1);
insert into scoreboard values(2,7,55,6,2,2);
insert into scoreboard values(2,7,37,32,3,3);
insert into scoreboard values(2,8,38,43,1,1);
insert into scoreboard values(2,8,56,30,2,2);
insert into scoreboard values(2,8,38,44,3,3);
insert into scoreboard values(2,9,45,33,1,1);
insert into scoreboard values(2,9,39,34,2,2);
insert into scoreboard values(2,9,51,35,3,3);
insert into scoreboard values(2,10,40,36,1,1);
insert into scoreboard values(2,10,40,32,1,1);
insert into scoreboard values(2,10,52,7,2,2);
insert into scoreboard values(2,10,52,37,2,2);
insert into scoreboard values(2,11,41,44,1,1);
insert into scoreboard values(2,11,41,43,1,1);
insert into scoreboard values(2,11,47,45,2,2);
insert into scoreboard values(2,11,47,46,2,2);
insert into scoreboard values(2,11,71,47,3,3);
insert into scoreboard values(2,11,71,48,3,3);
insert into scoreboard values(2,12,42,38,1,1);
insert into scoreboard values(2,12,42,39,1,1);
insert into scoreboard values(2,12,66,40,2,2);
insert into scoreboard values(2,12,66,41,2,2);
insert into scoreboard values(2,12,54,35,3,3);
insert into scoreboard values(2,12,54,42,3,3);
insert into scoreboard values(3,13,85,49,1,1);
insert into scoreboard values(3,13,73,32,2,2);
insert into scoreboard values(3,13,73,31,3,3);
insert into scoreboard values(3,14,74,43,1,1);
insert into scoreboard values(3,14,80,64,2,2);
insert into scoreboard values(3,15,75,52,2,2);
insert into scoreboard values(3,16,76,54,1,1);
insert into scoreboard values(3,16,76,32,1,1);
insert into scoreboard values(3,16,88,49,2,2);
insert into scoreboard values(3,16,88,55,2,2);
insert into scoreboard values(3,17,77,43,1,1);
insert into scoreboard values(3,17,77,66,1,1);
insert into scoreboard values(3,17,107,47,2,2);
insert into scoreboard values(3,17,107,68,2,2);
insert into scoreboard values(3,17,95,69,3,3);
insert into scoreboard values(3,17,95,70,3,3);
insert into scoreboard values(3,18,78,58,1,1);
insert into scoreboard values(3,18,78,59,1,1);
insert into scoreboard values(3,18,108,60,2,2);
insert into scoreboard values(3,18,108,61,2,2);
insert into scoreboard values(4,19,109,58,1,1);
insert into scoreboard values(4,19,133,40,3,3);
insert into scoreboard values(4,20,110,79,1,1);
insert into scoreboard values(4,20,110,80,2,2);
insert into scoreboard values(4,20,128,69,3,3);
insert into scoreboard values(4,21,111,73,1,1);
insert into scoreboard values(4,21,141,61,2,2);
insert into scoreboard values(4,22,112,58,3,3);
insert into scoreboard values(4,22,112,32,3,3);
insert into scoreboard values(4,23,113,43,1,1);
insert into scoreboard values(4,23,113,81,1,1);
insert into scoreboard values(4,23,131,69,3,3);
insert into scoreboard values(4,23,131,70,3,3);
insert into scoreboard values(4,24,114,73,1,1);
insert into scoreboard values(4,24,114,38,1,1);

commit;